version: '3'

services:
  db:
    image: postgres:10
    volumes:
      - "db-data:/var/lib/postgresql/data"
  web:
    build: .
    command: gunicorn src.myproject.wsgi:application -b 0.0.0.0:8000
    volumes:
      - web-static:/app/staticfiles
      - web-media:/app/media
    depends_on:
      - db
  nginx:
    image: nginx:1.13
    volumes:
      - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf
      - web-static:/usr/share/nginx/html/static
      - web-media:/usr/share/nginx/html/media
    depends_on:
      - web
    ports:
      - "80:80"

volumes:
  db-data:
  web-media:
  web-static:
