version: '3'

services:
  db:
    image: postgres:10
    volumes:
      - "db-data:/var/lib/postgresql/data"
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - web-static:/app/staticfiles
      - web-media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db-data:
  web-media:
  web-static:
